development:
  adapter: postgresql
  encoding: unicode
  database: reme_dev
  pool: 5
  username: hoote
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: reme_pro
  pool: 5
  username: hoote
  password:
